### ISSUE TITLE
Looks like popups are partially hidden under the new menu. 

### ISSUE THREAD

**Issue by kklauder** [dfensgmbh/biz.dfch.LS.PushMenu#1]
I noticed on my phone that popups are partially hidden under the new menu

**Comment by ckreissl** [comment]
Hi. You are right! Thx for your feedback.
You can fix this by setting the z-index to 100 in pushmenu.css:
.multilevelpushmenu_wrapper {
    z-index: 100;
}

**Comment by dfch** [comment]
MeinProTip

Wenn Dein Hinweis das Problem wirklich löst, dann änder auch gleich den Code und mach einen Commit.

From: Carsten Kreissl
Sent: Freitag, 6. Februar 2015 20:54
To: dfensgmbh/biz.dfch.LS.PushMenu
Reply To: dfensgmbh/biz.dfch.LS.PushMenu
Subject: Re: [biz.dfch.LS.PushMenu] Looks like popups are partially hidden under the new menu. (#1)



Hi. You are right! Thx for your feedback.
You can fix this by setting the z-index to 100 in pushmenu.css:
.multilevelpushmenu_wrapper {
z-index: 100;
}

-

**Comment by kklauder** [comment]
that worked... Thanks

**Comment by ckreissl** [comment]
You are welcome. :-)
