### ISSUE TITLE
phone tablet open/close menu issue

### ISSUE THREAD

**Issue by kklauder** [dfensgmbh/biz.dfch.LS.PushMenu#2]
Hi, I noticed using a phone or tablet that when opening or closing the menu, its seems to not respond that well to a tap. Some times I have to tap a couple of times to get the menu to open or close.

**Comment by ckreissl** [comment]
Hi, which devices do you use?

**Comment by kklauder** [comment]
currently testing on an iphone 5 and a ipad mini v1. Also happened on my wifes galaxy s5 and my daughters lg3.

**Comment by ckreissl** [comment]
ok. try this http://multi-level-push-menu.make.rs/demo/basichtml/basichtml.html
this is the original demo website from the menu (I only show how to get this into lightswitch...)

**Comment by kklauder** [comment]
the demo seems to work ok...

**Comment by ckreissl** [comment]
what about my demo?
https://lsdemo.netz-werke.net/biz.dfch.ls.pushmenu/htmlclient/

**Comment by ckreissl** [comment]
on my iPhone 5S it works fine...

**Comment by kklauder** [comment]
https://lsdemo.netz-werke.net/biz.dfch.ls.pushmenu/htmlclient/

That works ok on my iphone

**Comment by ckreissl** [comment]
And the other devices?

**Comment by kklauder** [comment]
my ipad mini is fine also... can't test any other devices... let me do some more testing then if you haven't changed anything. I have a different google font assigned maybe that has something to do with it. Thanks any way...

**Comment by ckreissl** [comment]
ok. you are welcome. 
I will close this issue and my demo site.
